### ISSUE TITLE
openaiライブラリのバージョン

### ISSUE THREAD

**Issue by shohei1029** [07JP27/openai-client#1]
@07JP27 
すみません、ご存じの通りopenaiライブラリが1.xで書き方が変わってしまったので、どちらかの対応をお願いしてもよろしいでしょうか (いやお前が書けよという話ですが・・・)
- requirements.txt を `openai==0.28.1` にする
- app.pyを1.xに書き換え (同時にrequirements.txtもバージョン固定する)

**Comment by 07JP27** [comment]
1に書き換えたいですね
